### PR TITLE
Fix Vernier sensors finalization.

### PR DESCRIPTION
**Pull request by ezio-melotti**
This PR fixes the Vernier sensors finalization by calling `device.close()` on `exit`.

### CODE REVIEW

**Review by granawkins — COMMENTED** [review]
I was looking at the original gdx package and they also call `godirect.quit()` (https://github.com/VernierST/godirect-examples/blob/a90b6be8536e7f4a510fc56e6a35c2671de34f20/python/gdx/gdx.py#L696). If things are still slow on close/start, we could wrap line 26 in `vernier.py` in a `try` and have a `finally` with `gd.quit()`.

**Comment by ezio-melotti** [comment]
I can test that and if it works I can add it too, but otherwise this PR seems to fix the problem I was seeing.

**Comment by ezio-melotti** [comment]
I updated the PR to also call `gd.quit()` and tested that it works.

**Comment by granawkins** [comment]
Awesomeo, looks good to me

**Pull request merged**
